spring:
  datasource:
    url: jdbc:h2:mem:course-app;DB_CLOSE_DELAY=-1
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
  h2.console:
    enabled: true
    path: /h2
  kafka:
    topic.name: course_app.json
    producer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
server.port: 8082

