name: code compliancy

on:
  pull_request:
    branches: [ "main", "ci-cd-pipeline" ]

jobs:  
  code-compliancy:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v3
    - uses: super-linter/super-linter@v5
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
